In [1]:
matrixA <- matrix(c(7,2,9,4,12,13), nrow =2,ncol=3)
matrixA

[,1] [,2] [,3]
[1,] 7    9    12  
[2,] 2    4    13

In [5]:
matrixB <- matrix(c(1,2,3,7,8,9,12,13,14,19,20,21), nrow =3, ncol =4)
matrixB

[,1] [,2] [,3] [,4]
[1,] 1    7    12   19  
[2,] 2    8    13   20  
[3,] 3    9    14   21

In [6]:
matrixA %*% matrixB

[,1] [,2] [,3] [,4]
[1,] 61   229  369  565 
[2,] 49   163  258  391

In [32]:
i <- c(2,4,6,8,4,5,2,1,9,0,4,6,7,4,3,2,1,9,10,3,7,9,6,0,1,3,5,6,7,8,9,10,2,3,6,8,9,10,6,7,4,3)
sort(i)

[1]  0  0  1  1  1  2  2  2  2  3  3  3  3  3  4  4  4  4  4  5  5  6  6  6  6
[26]  6  6  7  7  7  7  8  8  8  9  9  9  9  9 10 10 10